In [27]:
import numpy as np
import pandas as pd

In [28]:
weight_summary = pd.read_csv('data/2025-06-19-10_weights_summary.csv')
weight_summary

,name,shape,mean,std,min,max,norm,sparsity
0,seq_encoder.stem_conv.0.weight,"torch.Size([256, 4, 1, 8])",0.000979,0.101977,-0.188023,0.180976,9.229752,0.0
1,seq_encoder.stem_conv.0.bias,torch.Size([256]),-0.001556,0.098583,-0.176509,0.175424,1.574436,0.0
2,seq_encoder.conv_tower.0.0.weight,"torch.Size([128, 256, 1, 3])",-0.000013,0.021178,-0.047052,0.047359,6.639893,0.0
3,seq_encoder.conv_tower.0.0.bias,torch.Size([128]),-0.000100,0.021454,-0.039510,0.042399,0.241779,0.0
4,seq_encoder.conv_tower.0.1.weight,torch.Size([128]),1.000021,0.003547,0.992123,1.011226,11.314020,0.0
...,...,...,...,...,...,...,...,...
139,pToSplice.4.bias,torch.Size([1]),0.056108,NaN,0.056108,0.056108,0.056108,0.0
140,add_pos_conv.0.weight,"torch.Size([64, 67, 1])",0.000521,0.071086,-0.132853,0.133632,4.654494,0.0
141,add_pos_conv.0.bias,torch.Size([64]),0.003538,0.065381,-0.112171,0.118129,0.519721,0.0
142,add_pos_conv.2.weight,"torch.Size([64, 64, 1])",-0.000874,0.071967,-0.131390,0.134213,4.605677,0.0
143,add_pos_conv.2.bias,torch.Size([64]),-0.007927,0.059025,-0.118238,0.122181,0.472772,0.0

In [29]:
# check which weight norms are greater than 1
weight_summary['norm_gt_1'] = weight_summary['norm'] > 1
# filter the DataFrame to show only those rows
weight_summary_gt_1 = weight_summary[weight_summary['norm_gt_1']]
weight_summary_gt_1.sort_values('norm', ascending=False)

,name,shape,mean,std,min,max,norm,sparsity,norm_gt_1
30,segment_encoder.conv_tower.0.1.weight,torch.Size([128]),1.000089,0.003163,0.989233,1.008015,11.314769,0.0,True
4,seq_encoder.conv_tower.0.1.weight,torch.Size([128]),1.000021,0.003547,0.992123,1.011226,11.314020,0.0,True
48,segment_encoder.conv_tower.6.1.weight,torch.Size([128]),0.999934,0.004294,0.987074,1.013343,11.313068,0.0,True
22,seq_encoder.conv_tower.6.1.weight,torch.Size([128]),0.999865,0.003922,0.988209,1.009679,11.312267,0.0,True
52,attn_encoder.0.self_attn.in_proj_weight,"torch.Size([192, 64])",0.000198,0.088339,-0.162859,0.170018,9.792067,0.0,True
...,...,...,...,...,...,...,...,...,...
27,segment_encoder.stem_conv.0.bias,torch.Size([256]),-0.001199,0.103203,-0.178165,0.173469,1.648137,0.0,True
1,seq_encoder.stem_conv.0.bias,torch.Size([256]),-0.001556,0.098583,-0.176509,0.175424,1.574436,0.0,True
61,attn_encoder.0.ff.0.bias,torch.Size([256]),-0.000690,0.073762,-0.124868,0.136841,1.177938,0.0,True
73,attn_encoder.1.ff.0.bias,torch.Size([256]),-0.000818,0.073756,-0.124030,0.131047,1.177865,0.0,True
85,attn_encoder.2.ff.0.bias,torch.Size([256]),-0.001096,0.073642,-0.126623,0.124898,1.176099,0.0,True

In [30]:
# get rows where name contains attn_
weight_summary_attn = weight_summary[weight_summary['name'].str.contains('attn_')]
# sort by norm in descending order
weight_summary_attn.sort_values('norm', ascending=False)

,name,shape,mean,std,min,max,norm,sparsity,norm_gt_1
52,attn_encoder.0.self_attn.in_proj_weight,"torch.Size([192, 64])",0.000198,0.088339,-0.162859,0.170018,9.792067,0.0,True
64,attn_encoder.1.self_attn.in_proj_weight,"torch.Size([192, 64])",0.000253,0.088221,-0.161357,0.159994,9.779033,0.0,True
76,attn_encoder.2.self_attn.in_proj_weight,"torch.Size([192, 64])",0.000272,0.088220,-0.161430,0.162492,9.778992,0.0,True
60,attn_encoder.0.ff.0.weight,"torch.Size([256, 64])",-0.000132,0.072015,-0.133806,0.133310,9.217630,0.0,True
72,attn_encoder.1.ff.0.weight,"torch.Size([256, 64])",-0.000086,0.072006,-0.131141,0.133294,9.216554,0.0,True
84,attn_encoder.2.ff.0.weight,"torch.Size([256, 64])",-0.000116,0.071954,-0.130983,0.131071,9.209804,0.0,True
56,attn_encoder.0.norm1.weight,torch.Size([64]),0.999448,0.003823,0.992058,1.007586,7.995644,0.0,True
58,attn_encoder.0.norm2.weight,torch.Size([64]),0.998913,0.003531,0.990963,1.008047,7.991350,0.0,True
70,attn_encoder.1.norm2.weight,torch.Size([64]),0.998543,0.003199,0.991247,1.006571,7.988382,0.0,True
80,attn_encoder.2.norm1.weight,torch.Size([64]),0.998275,0.002359,0.992635,1.003700,7.986221,0.0,True
68,attn_encoder.1.norm1.weight,torch.Size([64]),0.998076,0.002708,0.990114,1.004035,7.984637,0.0,True
82,attn_encoder.2.norm2.weight,torch.Size([64]),0.997873,0.002372,0.993243,1.003463,7.983007,0.0,True
62,attn_encoder.0.ff.2.weight,"torch.Size([64, 256])",0.000137,0.036181,-0.069637,0.073887,4.631083,0.0,True
74,attn_encoder.1.ff.2.weight,"torch.Size([64, 256])",0.000114,0.036130,-0.069439,0.069128,4.624490,0.0,True
54,attn_encoder.0.self_attn.out_proj.weight,"torch.Size([64, 64])",-0.000660,0.072263,-0.130235,0.133220,4.624457,0.0,True
86,attn_encoder.2.ff.2.weight,"torch.Size([64, 256])",0.000080,0.036084,-0.070956,0.068608,4.618630,0.0,True
66,attn_encoder.1.self_attn.out_proj.weight,"torch.Size([64, 64])",-0.000648,0.072119,-0.129514,0.128249,4.615214,0.0,True
78,attn_encoder.2.self_attn.out_proj.weight,"torch.Size([64, 64])",-0.000616,0.072070,-0.129022,0.130823,4.612114,0.0,True
61,attn_encoder.0.ff.0.bias,torch.Size([256]),-0.000690,0.073762,-0.124868,0.136841,1.177938,0.0,True
73,attn_encoder.1.ff.0.bias,torch.Size([256]),-0.000818,0.073756,-0.124030,0.131047,1.177865,0.0,True
85,attn_encoder.2.ff.0.bias,torch.Size([256]),-0.001096,0.073642,-0.126623,0.124898,1.176099,0.0,True
63,attn_encoder.0.ff.2.bias,torch.Size([64]),0.008947,0.039753,-0.065384,0.064690,0.323550,0.0,False
75,attn_encoder.1.ff.2.bias,torch.Size([64]),0.008878,0.039706,-0.065418,0.064024,0.323062,0.0,False
87,attn_encoder.2.ff.2.bias,torch.Size([64]),0.008839,0.039610,-0.064590,0.063846,0.322251,0.0,False
53,attn_encoder.0.self_attn.in_proj_bias,torch.Size([192]),0.000367,0.002994,-0.008855,0.013723,0.041691,0.0,False
77,attn_encoder.2.self_attn.in_proj_bias,torch.Size([192]),0.000037,0.002432,-0.007338,0.007781,0.033616,0.0,False
65,attn_encoder.1.self_attn.in_proj_bias,torch.Size([192]),0.000168,0.002152,-0.007618,0.010907,0.029837,0.0,False
57,attn_encoder.0.norm1.bias,torch.Size([64]),0.000457,0.002901,-0.007099,0.006877,0.023312,0.0,False
83,attn_encoder.2.norm2.bias,torch.Size([64]),0.000384,0.002586,-0.005454,0.008121,0.020750,0.0,False
71,attn_encoder.1.norm2.bias,torch.Size([64]),0.000153,0.002540,-0.008504,0.004245,0.020196,0.0,False
59,attn_encoder.0.norm2.bias,torch.Size([64]),-0.000011,0.002433,-0.006894,0.004149,0.019309,0.0,False
55,attn_encoder.0.self_attn.out_proj.bias,torch.Size([64]),0.000172,0.002318,-0.004205,0.004665,0.018450,0.0,False
69,attn_encoder.1.norm1.bias,torch.Size([64]),0.000279,0.002290,-0.004215,0.004568,0.018309,0.0,False
67,attn_encoder.1.self_attn.out_proj.bias,torch.Size([64]),0.000158,0.002211,-0.005935,0.004329,0.017592,0.0,False
79,attn_encoder.2.self_attn.out_proj.bias,torch.Size([64]),0.000150,0.002205,-0.006627,0.004295,0.017545,0.0,False
81,attn_encoder.2.norm1.bias,torch.Size([64]),0.000246,0.001959,-0.003380,0.005193,0.015670,0.0,False

In [31]:
# get rows where name contains pTo
weight_summary_attn = weight_summary[weight_summary['name'].str.contains('pTo')]
# sort by norm in descending order
weight_summary_attn.sort_values('norm', ascending=False)

,name,shape,mean,std,min,max,norm,sparsity,norm_gt_1
126,pToExpr.2.weight,"torch.Size([128, 128])",0.000038,0.051385,-0.106942,0.109512,6.577145,0.0,True
124,pToExpr.0.weight,"torch.Size([128, 73])",0.000209,0.067811,-0.142616,0.143210,6.554609,0.0,True
136,pToSplice.2.weight,"torch.Size([128, 128])",-0.000221,0.051045,-0.088381,0.088387,6.533652,0.0,True
130,pToSpliceBinary.0.weight,"torch.Size([128, 73])",0.000875,0.067212,-0.116991,0.117034,6.497164,0.0,True
134,pToSplice.0.weight,"torch.Size([128, 73])",0.000550,0.067107,-0.117029,0.117028,6.486726,0.0,True
135,pToSplice.0.bias,torch.Size([128]),0.002600,0.071628,-0.116854,0.115755,0.807744,0.0,False
131,pToSpliceBinary.0.bias,torch.Size([128]),0.003866,0.065525,-0.116995,0.113836,0.739719,0.0,False
125,pToExpr.0.bias,torch.Size([128]),-0.001553,0.065307,-0.113993,0.116624,0.736184,0.0,False
128,pToExpr.4.weight,"torch.Size([1, 128])",-0.011961,0.055654,-0.102536,0.088322,0.641620,0.0,False
137,pToSplice.2.bias,torch.Size([128]),0.005339,0.054849,-0.087453,0.088334,0.621057,0.0,False
127,pToExpr.2.bias,torch.Size([128]),0.001928,0.054133,-0.085874,0.087535,0.610437,0.0,False
132,pToSpliceBinary.2.weight,"torch.Size([1, 128])",0.006320,0.051862,-0.087989,0.085326,0.588812,0.0,False
138,pToSplice.4.weight,"torch.Size([1, 128])",-0.007065,0.051157,-0.087891,0.084440,0.582023,0.0,False
133,pToSpliceBinary.2.bias,torch.Size([1]),0.086154,NaN,0.086154,0.086154,0.086154,0.0,False
129,pToExpr.4.bias,torch.Size([1]),-0.076423,NaN,-0.076423,-0.076423,0.076423,0.0,False
139,pToSplice.4.bias,torch.Size([1]),0.056108,NaN,0.056108,0.056108,0.056108,0.0,False